### ISSUE TITLE
Connection to zabbix database failure

### ISSUE THREAD

**Issue by crowfeatherjoe** [USBAkimbo/Random#1]
`7:20240506:223314.479 [Z3001] connection to database 'zabbix' failed: [1045] Access denied for user 'zabbix'@'172.25.0.3' (using password: YES)`

unable to log into zabbix using predefined credentials in .env file. 

```
# .env file

# Database settings
MYSQL_USER=zabbix
MYSQL_PASSWORD=password
MYSQL_ROOT_PASSWORD=password

# Zabbix data path (replace with the correct absolute path)
ZABBIX_DATA_PATH=/var/lib/docker/zabix

# Zabbix server settings
ZBX_STARTPINGERS=5
```

**Comment by W1BTR** [comment]
I think youre confusing the database login with zabbix.

Zabbix (and many other applications out there) store there data in a database software that is all backend stuff. The docker compose helps you set up a mysql (a type of database) server. Those login details are the login details the zabbix server uses to log in to the mysql database.

The actual zabbix login will be `Admin` and `zabbix` by default I believe.
